# Generated by Django 5.1 on 2024-09-19 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0006_rename_products_cartitem_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
