# Generated by Django 5.1 on 2024-09-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0007_delete_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
