# Generated by Django 5.1 on 2024-09-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0008_subcategory_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='url',
        ),
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
