# Generated by Django 5.1 on 2024-09-24 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0009_remove_subcategory_url_category_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='url',
        ),
    ]
